<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913191105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CVs (no JSON attribute storage; values come from ProfileAttribute) and CV likes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, position_id INT NOT NULL, status VARCHAR(16) NOT NULL, published_at DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CV_PROFILE_POSITION ON cv (profile_id, position_id)');
        $this->addSql('CREATE INDEX IDX_CV_POSITION ON cv (position_id)');
        $this->addSql('CREATE INDEX IDX_CV_STATUS ON cv (status)');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CV_LIKE_RECRUITER ON cv_like (cv_id, recruiter_id)');
        $this->addSql('CREATE INDEX IDX_CV_LIKE_CV ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CV_LIKE_RECRUITER ON cv_like (recruiter_id)');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_CV FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_RECRUITER FOREIGN KEY (recruiter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CV_LIKE_RECRUITER');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CV_LIKE_CV');
        $this->addSql('DROP TABLE cv_like');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_CV_POSITION');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_CV_PROFILE');
        $this->addSql('DROP TABLE cv');
    }
}