<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds salesforce_connection table so Profile can remember the IDs of
 * the Salesforce Account + Contact created by the first Export. This
 * makes subsequent exports idempotent (PATCH on the same records
 * instead of duplicate POSTs).
 */
final class Version20261006144753 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add salesforce_connection table for tracking Account/Contact IDs per Profile.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE salesforce_connection (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                profile_id INT NOT NULL,
                salesforce_account_id VARCHAR(32) NOT NULL,
                salesforce_contact_id VARCHAR(32) DEFAULT NULL,
                last_exported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                last_error TEXT DEFAULT NULL,
                PRIMARY KEY (id),
                CONSTRAINT fk_salesforce_connection_profile
                    FOREIGN KEY (profile_id) REFERENCES profile (id)
                    ON DELETE CASCADE
            )
        ');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SALESFORCE_CONNECTION_PROFILE ON salesforce_connection (profile_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE salesforce_connection');
    }
}
