<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912165547 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Positions, position_attribute (M:N), position_access_rule';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(128) NOT NULL, short_description VARCHAR(512) NOT NULL, company VARCHAR(128) DEFAULT NULL, level VARCHAR(16) DEFAULT NULL, is_public BOOLEAN DEFAULT TRUE NOT NULL, max_projects INT DEFAULT 5 NOT NULL, project_tag_filter JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_POSITION_LEVEL ON position (level)');
        $this->addSql('CREATE INDEX IDX_POSITION_COMPANY ON position (company)');

        $this->addSql("CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_definition_id INT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_ATTRIBUTE_PAIR ON position_attribute (position_id, attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_POS ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_DEF ON position_attribute (attribute_definition_id)');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_POS FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_DEF FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_definition_id INT NOT NULL, operator VARCHAR(32) NOT NULL, value JSON NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_POSITION_RULE_POS ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_RULE_DEF ON position_access_rule (attribute_definition_id)');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_RULE_POS FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_RULE_DEF FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_POSITION_RULE_DEF');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_POSITION_RULE_POS');
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_POSITION_ATTRIBUTE_DEF');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_POSITION_ATTRIBUTE_POS');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE position');
    }
}