<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260908143022 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Attribute library (category, definition, option), profile_attribute with typed columns, user.is_blocked';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("CREATE TABLE attribute_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ATTRIBUTE_CATEGORY_CODE ON attribute_category (code)');

        $this->addSql("CREATE TABLE attribute_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(512) DEFAULT '' NOT NULL, data_type VARCHAR(32) NOT NULL, category_id INT NOT NULL, required BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ATTRIBUTE_DEF_NAME ON attribute_definition (name)');
        $this->addSql('CREATE INDEX IDX_ATTRIBUTE_DEF_CATEGORY ON attribute_definition (category_id)');
        $this->addSql('ALTER TABLE attribute_definition ADD CONSTRAINT FK_ATTRIBUTE_DEF_CATEGORY FOREIGN KEY (category_id) REFERENCES attribute_category (id) ON DELETE RESTRICT NOT DEFERRABLE');

        $this->addSql("CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attribute_definition_id INT NOT NULL, value VARCHAR(128) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_ATTRIBUTE_OPTION_DEFINITION ON attribute_option (attribute_definition_id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_ATTRIBUTE_OPTION_DEFINITION FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE profile_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, attribute_definition_id INT NOT NULL, version INT DEFAULT 1 NOT NULL, string_value VARCHAR(255) DEFAULT NULL, markdown_text TEXT DEFAULT NULL, numeric_value NUMERIC(12, 4) DEFAULT NULL, date_value DATE DEFAULT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, boolean_value BOOLEAN DEFAULT NULL, image_url VARCHAR(512) DEFAULT NULL, selected_option_id INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROFILE_ATTRIBUTE_PROFILE_DEF ON profile_attribute (profile_id, attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_PROFILE_ATTRIBUTE_DEFINITION ON profile_attribute (attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_PROFILE_ATTRIBUTE_OPTION ON profile_attribute (selected_option_id)');
        $this->addSql('ALTER TABLE profile_attribute ADD CONSTRAINT FK_PROFILE_ATTRIBUTE_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_attribute ADD CONSTRAINT FK_PROFILE_ATTRIBUTE_DEFINITION FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_attribute ADD CONSTRAINT FK_PROFILE_ATTRIBUTE_OPTION FOREIGN KEY (selected_option_id) REFERENCES attribute_option (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('ALTER TABLE "user" ADD COLUMN is_blocked BOOLEAN DEFAULT FALSE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" DROP COLUMN is_blocked');
        $this->addSql('ALTER TABLE profile_attribute DROP CONSTRAINT FK_PROFILE_ATTRIBUTE_OPTION');
        $this->addSql('ALTER TABLE profile_attribute DROP CONSTRAINT FK_PROFILE_ATTRIBUTE_DEFINITION');
        $this->addSql('ALTER TABLE profile_attribute DROP CONSTRAINT FK_PROFILE_ATTRIBUTE_PROFILE');
        $this->addSql('DROP TABLE profile_attribute');
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_ATTRIBUTE_OPTION_DEFINITION');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('ALTER TABLE attribute_definition DROP CONSTRAINT FK_ATTRIBUTE_DEF_CATEGORY');
        $this->addSql('DROP TABLE attribute_definition');
        $this->addSql('DROP TABLE attribute_category');
    }
}
