<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Per-Position API tokens for the Odoo integration. Each row holds
 * only the SHA-256 hash of a random secret; the plaintext is shown
 * exactly once at creation and never persisted. Cascade-delete from
 * `position` keeps tokens from outliving their Position.
 */
final class Version20261009063514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add position_api_token table for Odoo bearer credentials.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE position_api_token (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                position_id INT NOT NULL,
                token_hash VARCHAR(64) NOT NULL,
                prefix VARCHAR(8) NOT NULL,
                label VARCHAR(255) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id),
                CONSTRAINT fk_position_api_token_position
                    FOREIGN KEY (position_id) REFERENCES position (id)
                    ON DELETE CASCADE
            )
        ');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_API_TOKEN_HASH ON position_api_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_POSITION_API_TOKEN_POSITION ON position_api_token (position_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE position_api_token');
    }
}
