<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260910100214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Profile built-in fields, projects, technology tags';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE profile ADD COLUMN first_name VARCHAR(128) DEFAULT NULL");
        $this->addSql("ALTER TABLE profile ADD COLUMN last_name VARCHAR(128) DEFAULT NULL");
        $this->addSql("ALTER TABLE profile ADD COLUMN location VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE profile ADD COLUMN photo_url VARCHAR(512) DEFAULT NULL");

        $this->addSql("CREATE TABLE technology_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TECHNOLOGY_TAG_NAME ON technology_tag (name)');

        $this->addSql("CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, name VARCHAR(128) NOT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, markdown_description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_PROJECT_PROFILE ON project (profile_id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_PROJECT_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE project_technology_tag (project_id INT NOT NULL, technology_tag_id INT NOT NULL, PRIMARY KEY (project_id, technology_tag_id))");
        $this->addSql('CREATE INDEX IDX_PROJECT_TAG_PROJECT ON project_technology_tag (project_id)');
        $this->addSql('CREATE INDEX IDX_PROJECT_TAG_TAG ON project_technology_tag (technology_tag_id)');
        $this->addSql('ALTER TABLE project_technology_tag ADD CONSTRAINT FK_PROJECT_TAG_PROJECT FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_technology_tag ADD CONSTRAINT FK_PROJECT_TAG_TAG FOREIGN KEY (technology_tag_id) REFERENCES technology_tag (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_technology_tag DROP CONSTRAINT FK_PROJECT_TAG_TAG');
        $this->addSql('ALTER TABLE project_technology_tag DROP CONSTRAINT FK_PROJECT_TAG_PROJECT');
        $this->addSql('DROP TABLE project_technology_tag');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_PROJECT_PROFILE');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE technology_tag');
        $this->addSql('ALTER TABLE profile DROP COLUMN photo_url');
        $this->addSql('ALTER TABLE profile DROP COLUMN location');
        $this->addSql('ALTER TABLE profile DROP COLUMN last_name');
        $this->addSql('ALTER TABLE profile DROP COLUMN first_name');
    }
}